version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  danger:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec danger --verbose

workflows:
  danger:
    jobs:
      - danger